### ISSUE TITLE
split-sync should set language

### ISSUE THREAD

**Issue by bsussman** [mupchrch/split-diff#144] opened 2018-03-23 19:13 UTC
atom 1.26.0B0
split-diff 1.5.2

To see the diff with the new pane colorized, I must manually set the language (the tabname is 'untitled').

split-sync should track and set to match the language of the diffed pane.

**Comment by mupchrch** [comment] 2018-09-12 13:42
Closing as I am unable to reproduce. Please reopen this issue if you are still experiencing this. Thank you!

**Closed by mupchrch** 2018-09-12 13:42 UTC
