### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by ramannanda9** [mupchrch/split-diff#152] opened 2018-11-04 00:07 UTC
Open file 
toggle splitdiff 
paste text.
``` C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11
Hide Stack Trace
TypeError: Cannot read property 'tags' of undefined
    at TextMateHighlightIterator.seek (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:557244)
    at ScreenLineBuilder.buildScreenLines (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:14:1102792)
    at DisplayLayer.getScreenLines (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:14:89276)
    at DisplayLayer.getScreenLine (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:14:89173)
    at TextEditor.screenLineForScreenRow (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:13891)
    at TextEditorComponent.requestHorizontalMeasurement (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:104398)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:69473)
    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:107031)
    at TextEditorComponent.screenPositionForMouseEvent (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:98290)
    at TextEditorComponent.didMouseDownOnContent (C:\Users\raman\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:11:94850)```

**Comment by jaibatrik** [comment] 2018-12-03 09:38
Duplicate of #151

**Comment by mupchrch** [comment] 2019-01-08 15:47
Closing as duplicate.

**Closed by mupchrch** 2019-01-08 15:47 UTC
