### ISSUE TITLE
The plugin conflict 

### ISSUE THREAD

**Issue by linjialiang** [mupchrch/split-diff#146] opened 2018-04-22 07:44 UTC
The plugin conflict 
`git-time-machine`  `split-diff`  

embody:
> Using shortcut keys(`ctrl-alt-t`) or other operations can cause the `atom` to crash.

plugin list:
```shell
├── activate-power-mode@2.7.0
├── advanced-open-file@0.16.8
├── atom-beautify@0.32.2
├── atom-clock@0.1.16
├── atom-html-preview@0.2.5
├── atom-ide-ui@0.11.0
├── atom-material-syntax@1.0.8
├── atom-minify@0.8.0
├── autocomplete-paths@2.12.2
├── autoprefixer@3.7.1
├── city-lights-syntax@1.1.8
├── color-picker@2.3.0
├── docblockr@0.13.7
├── emmet@2.4.3
├── ex-mode@0.18.0
├── file-icons@2.1.18
├── git-blame@1.6.0
├── git-history@3.3.0
├── git-plus@7.10.2
├── git-time-machine@1.5.9
├── highlight-column@0.5.4
├── highlight-line@0.12.0
├── highlight-selected@0.13.1
├── ide-php@0.7.14
├── ide-typescript@0.7.6
├── markdown-scroll-sync@2.1.2
├── merge-conflicts@1.4.5
├── minimap@4.29.8
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── minimap-split-diff@0.3.7
├── monokai@0.24.0
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── project-viewer@1.3.1
├── relative-numbers@0.9.0
├── remote-ftp@2.1.4
├── split-diff@1.5.2
├── Sublime-Style-Column-Selection@1.7.4
├── sync-settings@0.8.6
├── tree-view-git-status@1.5.0
└── vim-mode-plus@1.32.0
```

**Comment by mupchrch** [comment] 2018-07-30 17:49
@linjialiang I am not seeing this issue. Do you have any more specific steps to reproduce?

**Comment by mupchrch** [comment] 2018-09-12 13:41
Closing as I was not able to reproduce. Please reopen if you are still seeing this. Thanks!

**Closed by mupchrch** 2018-09-12 13:41 UTC

**Comment by linjialiang** [comment] 2018-09-15 05:48
> ok! This issue has been resolved by plug-in maintainers.
