### ISSUE TITLE
Error Spam When File Encoding Set Incorrectly

### ISSUE THREAD

**Issue by Michael-Thibault** [mupchrch/split-diff#67] opened 2016-08-10 10:14 UTC
Running split-diff I'm getting spammed by the following errors. Not immediately, but usually once I scroll past a removed text diff (red).

The spamming stops only as long as I don't move the cursor over the minimap (split-diff minimap plugin is disabled) or scroll. Doing either of those results in more errors. The errors I'm getting occur in pairs (oddly enough), though sometimes they are different.

**Edit**: I figured-out what seems to be the root cause. The files were opened with UTF-8, and they were in fact encoded as UTF-16 LE. With the file encodings set correctly, none of the below errors occur. Though it might be nifty if split-diff could catch this somehow. Took a bit of guesswork on my part (it wasn't immediately apparent that UTF-8 was wrong).
# First Pair

**Atom Version**: 1.9.7
**System**: Microsoft Windows 10 Home
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'offsetTop' of null

```
At C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:82

TypeError: Cannot read property 'offsetTop' of null
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.measureBlockDecorations (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:82:29)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:274:73)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:225:9)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:3:61
```
### Commands

```
  2x -5:58.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -5:52.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -5:49.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:48.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:48.3.0 split-diff:enable (atom-text-editor.editor)
  6x -5:47.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -5:14.7.0 pane:split-right (ul.list-inline.tab-bar.inset-panel)
  7x -5:14.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -4:57.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -4:55.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:54 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:54 split-diff:enable (atom-text-editor.editor)
  2x -3:51.1.0 split-diff:next-diff (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -3:16.5.0 command-palette:toggle (atom-text-editor.editor)
     -3:13.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:12.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:111

TypeError: Cannot read property 'classList' of null
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.updateBlockDecorationNode (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:111:44)
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.updateSync (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:62:30)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:246:15)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:221:9)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:3:61
```
### Commands

```
  2x -5:58.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -5:52.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -5:50.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:48.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:48.8.0 split-diff:enable (atom-text-editor.editor)
  6x -5:48.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -5:15.2.0 pane:split-right (ul.list-inline.tab-bar.inset-panel)
  7x -5:15.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -4:57.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -4:55.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:54.5.0 split-diff:enable (atom-text-editor.editor)
  2x -3:51.6.0 split-diff:next-diff (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
     -3:17 command-palette:toggle (atom-text-editor.editor)
     -3:13.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -3:13.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.json": [
        "netkan",
        "ckan"
      ]
    },
    "disabledPackages": [
      "atom-ctags",
      "python-tools",
      "atom-commander",
      "aligner",
      "aligner-python",
      "todo-show",
      "markdown-preview-plus",
      "language-gfm",
      "linter-markdown",
      "sort-lines",
      "on-the-rocks",
      "minimap-split-diff"
    ],
    "packagesWithKeymapsDisabled": [
      "markdown-preview"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-vivid-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 15,
    "invisibles": {},
    "preferredLineLength": 120,
    "scrollPastEnd": true,
    "softWrapAtPreferredLineLength": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.3 (inactive)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.10 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-dark-fusion-syntax, v1.1.0 (inactive)
atom-formatter-jsbeautify, v1.1.2 (active)
atom-mermaid, v2.0.0 (inactive)
atom-reverser, v2.4.0 (inactive)
auto-detect-indentation, v1.1.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-python, v1.8.4 (active)
block-comment-lines, v0.2.4 (inactive)
bottom-dock, v0.4.4 (active)
build-tools, v4.5.2 (active)
color-picker, v2.2.2 (active)
compare-files, v0.6.2 (active)
ctags-status, v1.3.5 (active)
docblockr, v0.7.3 (active)
emmet-simplified, v2.5.0 (active)
file-icons, v1.7.17 (active)
file-types, v0.5.4-p1 (active)
git-log, v0.4.1 (active)
git-time-machine, v1.5.3 (inactive)
goto, v1.7.1 (inactive)
guess-indent, v0.1.0 (inactive)
highlight-selected, v0.11.2 (active)
imdone-atom, v1.3.29 (active)
imdone-atom-github, v0.1.11 (active)
indent-guide-improved, v1.4.9 (active)
java-generator, v2.2.0 (inactive)
java-importer, v1.4.1 (active)
jekyll, v1.4.2 (inactive)
kerbal-config, v0.4.1 (active)
language-gfm, v0.88.0 (inactive)
language-liquid, v0.5.1 (active)
language-lua, v0.9.4 (active)
language-markdown, v0.15.0 (active)
language-mediawiki, v2.0.0 (active)
language-minecraft-forge-cfg, v0.1.2 (active)
lines, v0.13.1 (inactive)
linter, v1.11.14 (active)
linter-javac, v1.9.4 (active)
linter-jsonlint, v1.3.0 (active)
linter-manager, v0.2.12 (active)
linter-markdown, v1.5.2 (inactive)
linter-python-pep8, v0.2.0 (active)
markdown-preview-enhanced, v0.7.9 (active)
markdown-writer, v2.4.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
minimap-bookmarks, v0.3.1 (active)
minimap-codeglance, v0.4.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
minimap-split-diff, v0.3.1 (inactive)
on-the-rocks, v2.1.0 (inactive)
one-dark-vivid-syntax, v1.1.2 (active)
open-recent, v5.0.0 (active)
pandoc-convert, v1.1.0 (active)
pigments, v0.31.2 (active)
project-plus, v0.9.0 (active)
release-notes, v0.53.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.1 (inactive)
slim-dark-ui, v0.12.0 (inactive)
split-diff, v1.0.3 (active)
symbol-gen, v1.3.1 (active)
sync-settings, v0.7.2 (active)
synced-sidebar, v0.4.3 (active)
terminal-plus, v0.14.5 (active)
todo-manager, v0.2.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
# Second Pair

**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of null

```
At C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:50

TypeError: Cannot read property 'remove' of null
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.updateSync (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:50:46)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:246:15)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:221:9)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:3:61
```
### Commands

```
     -3:28.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
```

**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'decoration' of undefined

```
At C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:78

TypeError: Cannot read property 'decoration' of undefined
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.measureBlockDecorations (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\block-decorations-component.js:78:66)
    at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:274:73)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:225:9)
    at C:\Users\mthibault\AppData\Local\atom\app-1.9.7\resources\app.asar\src\view-registry.js:3:61
```
### Commands

```
     -3:27.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-vivid-syntax.theme-one-dark-ui)
```

**Comment by mupchrch** [comment] 2016-09-26 01:57
@Michael-Thibault I have been having trouble reproducing this, would it be possible to attach two files so I can see this in action? Thanks, and great catch!

**Comment by mupchrch** [comment] 2017-02-20 19:58
Still unable to reproduce, hope it is okay if I close this issue. Please reopen if this is still happening for you!

**Closed by mupchrch** 2017-02-20 19:58 UTC
Labels: bug, help wanted
