### ISSUE TITLE
Live change altering wrong line

### ISSUE THREAD

**Issue by AnthonyMichaelc** [mupchrch/split-diff#88] opened 2017-01-27 00:34 UTC
In macOS Sierra running Atom 1.13.1 

When enabling split diff the preview I clicked any line and added code or tried adding spaces. The preview panel that pops up next to my file shows spaces added two lines up.

Basically if I add a line (for example another p tag) after the closing p tag 
div
    h2 testing h2 
       p 1 2 3 p
div 

it will look like this in the diff 

div 

    h2 testing h2
       p 1 2 3 p
div

**Comment by mupchrch** [comment] 2017-01-30 16:01
Hi @AnthonyMichaelc, I can't reproduce the issue, so I'm going to need to ask a bunch of questions!

1. Is the file tracked in git?
2. What packages are you using? (you can run `apm list --installed --bare` in console to get a list)
3. What is the file grammar set to? (can find this in the status bar at the bottom right of the atom window)
4. To clarify, the issue is that wherever you edit the left editor, the right editor gets an empty line added 2 lines up from that?

**Comment by mupchrch** [comment] 2017-03-27 03:17
Closing since I cannot reproduce, please reopen if this is still an issue!

**Closed by mupchrch** 2017-03-27 03:17 UTC
