### ISSUE TITLE
Deprecated use of position: 'absolute' and an assigned top and bottom

### ISSUE THREAD

**Issue by franklinrt** [mupchrch/split-diff#91] opened 2017-02-03 13:41 UTC
I just updated Atom to 1.13.1 and I am getting a deprecation warning from Split Diff.

Step 1: Open Atom
Step 2: Open a source file
Step 3: Toggle Split Diff

At this point I receive the following deprecation warning:

`atom core (1 deprecation)`

`Assigning editor 302's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.`

`TextEditorComponent.measureDimensions - /usr/share/atom/resources/app.asar/src/text-editor-component.js:1011:20`

`TextEditorComponent.becameVisible - /usr/share/atom/resources/app.asar/src/text-editor-component.js:295:12`

`TextEditorComponent.checkForVisibilityChange - /usr/share/atom/resources/app.asar/src/text-editor-component.js:993:16`

`atom-text-editor.attachedCallback - /usr/share/atom/resources/app.asar/src/text-editor-element.js:87:22`

`atom-pane-axis.childAdded - /usr/share/atom/resources/app.asar/src/pane-axis-element.js:95:12`

`Function.module.exports.Emitter.simpleDispatch - /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14`

**Comment by mupchrch** [comment] 2017-02-03 14:55
Hi @franklinrt thanks for the easy steps to reproduce! I think this is actually a problem with atom core itself. To prove this out, I ran the following code that split-diff essentially runs, but in the dev tools console:

`atom.workspace.paneForItem(atom.workspace.getActiveTextEditor()).splitRight({items:[atom.workspace.buildTextEditor()]})`

This seems like a perfectly reasonable thing to be able to do, so I will probably log an issue over on the atom project and link it back here!

**Comment by franklinrt** [comment] 2017-02-03 15:16
Apologies for assuming it was a Split Diff issue. I did some searching and found a few issues logged that linked to a bug [#13653](https://github.com/atom/atom/issues/13653). The suggested resolution is to clear the window state with `atom --clear-window-state`. That doesn't work as the moment you use the Split Diff Toggle the deprecation warning occurs again.

I appreciate if you let me know the issue you log on atom.

**Comment by mupchrch** [comment] 2017-02-10 04:10
Closing here since there is an issue logged over on atom core.

**Closed by mupchrch** 2017-02-10 04:10 UTC
