### ISSUE TITLE
Uncaught Error: Setting active pane that is not present in pane container

### ISSUE THREAD

**Issue by PipC** [mupchrch/split-diff#123] opened 2017-07-13 03:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [split-diff](https://github.com/mupchrch/split-diff) package 1.4.3

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At C:\Users\pipch\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane-container.js:257

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane-container.js:257:21)
    at Pane.module.exports.Pane.activate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane.js:911:20)
    at Pane.module.exports.Pane.focus (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane.js:290:25)
    at HTMLElement.<anonymous> (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane-element.js:51:25)
    at Object._setupVisibleEditors (/packages/split-diff/lib/split-diff.coffee:419:35)
    at /packages/split-diff/lib/split-diff.coffee:194:8)
```

### Commands

```
     -1:10.2.0 intentions:highlight (input.hidden-input)
     -1:09.9.0 core:save (input.hidden-input)
     -1:00.9.0 intentions:highlight (input.hidden-input)
     -1:00.7.0 core:copy (input.hidden-input)
  2x -0:53.5.0 editor:newline (input.hidden-input)
  2x -0:53 core:move-up (input.hidden-input)
     -0:52.7.0 intentions:highlight (input.hidden-input)
     -0:52.5.0 core:paste (input.hidden-input)
     -0:51.4.0 core:move-down (input.hidden-input)
     -0:45.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:45.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:44.9.0 core:backspace (input.hidden-input)
  2x -0:44.7.0 core:delete (input.hidden-input)
     -0:43.6.0 intentions:highlight (input.hidden-input)
     -0:43.4.0 core:save (input.hidden-input)
     -0:05.5.0 split-diff:enable (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.30.3 
atom-grails 1.0.1 
atom-material-ui 2.0.4 
atom-shell-commands 1.5.0 
busy-signal 1.4.3 
fold-functions 0.5.0 
format-sql 0.3.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-apache 1.7.0 
language-awk 0.1.12 
language-batch 0.4.0 
language-groovy 0.7.0 
language-tsql 0.19.0 
language-vue 0.23.0 
language-vue-component 0.5.0 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.3 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
quick-query-mssql 0.1.4 
split-diff 1.4.3 
Sublime-Style-Column-Selection 1.7.4 
tree-view-filter 0.5.3 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by mupchrch** [comment] 2017-08-17 19:19
Hi @PipC, any idea what some steps to reproduce are? I am not really sure how to get into this situation. Thanks!

**Comment by mupchrch** [comment] 2017-12-29 16:36
Hi @PipC I am going to close this since I never received a response. Please reopen and let me know if you've seen this more.

**Closed by mupchrch** 2017-12-29 16:36 UTC
Labels: cannot recreate
