### ISSUE TITLE
[git-time-machine] Cannot read property 'handleCursorChange' of null

### ISSUE THREAD

**Issue by darron1217** [mupchrch/split-diff#147] opened 2018-05-05 07:39 UTC
Original Issue https://github.com/littlebee/git-time-machine/issues/123
To get a better insight of this error, we need some help from split-diff guru :)

[Enter steps to reproduce:]

1. Install & Open git-time-machine
2. select a commit (it opens split diff)
3. close it
4. Wow! Error!

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Windows 10
**Thrown From**: [git-time-machine](https://github.com/littlebee/git-time-machine) package 1.5.9

### Stack Trace

Uncaught TypeError: Cannot read property 'handleCursorChange' of null

```
At C:\Users\darron\.atom\packages\git-time-machine\node_modules\split-diff\lib\split-diff.coffee:166

TypeError: Cannot read property 'handleCursorChange' of null
    at /packages/git-time-machine/node_modules/split-diff/lib/split-diff.coffee:166:18
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:2715:31)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.26.1/resources/app/src/selection.js:933:25)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.26.1/resources/app/src/selection.js:21:45)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/display-marker.js:248:33)
    at ~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/display-marker.js:53:32
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/marker.js:441:26)
    at Marker.module.exports.Marker.update (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/marker.js:374:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/marker-layer.js:290:24)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1705:85)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1009:20)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:955:20)
    at TextEditor.transact (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1839:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:2708:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:2519:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor-component.js:1808:25)
```

### Commands

```
     -8:32.4.0 editor:consolidate-selections (input.hidden-input)
     -8:32.4.0 core:cancel (input.hidden-input)
     -8:31.2.0 editor:consolidate-selections (input.hidden-input)
     -8:31.2.0 core:cancel (input.hidden-input)
     -8:30.1.0 editor:consolidate-selections (input.hidden-input)
     -8:30.1.0 core:cancel (input.hidden-input)
     -8:29 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:27.2.0 core:confirm (input.hidden-input)
     -8:27.1.0 settings-view:install-packages-and-themes (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:21.2.0 intentions:highlight (input.hidden-input)
     -8:21 command-palette:toggle (input.hidden-input)
     -8:19.5.0 core:confirm (input.hidden-input)
     -8:19.1.0 git-time-machine:toggle (input.hidden-input)
     -6:11.9.0 intentions:highlight (input.hidden-input)
  6x -6:11.7.0 core:copy (input.hidden-input)
     -6:04.4.0 git-time-machine:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-beautify 0.32.2 
atom-ide-ui 0.9.4 
atom-typescript 12.4.1 
autoclose-html 0.23.0 
autocomplete-clang 0.11.4 
autocomplete-ionic2-framework 0.3.2 
autocomplete-js-import 1.4.0 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
docblockr 0.13.7 
double-tag 1.1.0 
file-icons 2.1.18 
git-plus 7.10.2 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.0.0 
intentions 1.1.5 
language-blade 0.39.0 
language-docker 1.1.8 
language-ini 1.19.0 
language-log 1.10.1 
language-vue 0.23.1 
laravel 0.7.1 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.7 
multi-cursor 2.1.5 
php-integrator-annotations 1.2.0 
php-integrator-base 3.5.0 
php-integrator-refactoring 1.4.1 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
split-diff 1.5.2 
tool-bar 1.1.7 
typescript-modules-helper 0.8.0 
vue-autocomplete 0.1.1 
```

**Comment by mupchrch** [comment] 2018-07-30 17:36
@darron1217 is this still any issue? Not seeing it in v2 of `git-time-machine`.

**Comment by mupchrch** [comment] 2018-09-12 13:37
Closing as I cannot reproduce in the new version of `git-time-machine`.

**Closed by mupchrch** 2018-09-12 13:37 UTC
